"""Reset migrations for CockroachDB

Revision ID: 2f918f8c78ec
Revises: 8c55eb609cb0
Create Date: 2025-04-02 14:18:44.107724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f918f8c78ec'
down_revision = '8c55eb609cb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('geometry_columns')
    op.drop_table('geography_columns')
    op.drop_table('spatial_ref_sys')
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text('unique_rowid()'))
        batch_op.alter_column('user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_exercise_category'), ['category'], unique=False)
        batch_op.drop_table_comment(
        'exercise',
        existing_comment='Calculates y-intercept of the least-squares-fit linear equation determined by the (X, Y) pairs.',
        schema=None
    )

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text('unique_rowid()'))
        batch_op.drop_table_comment(
        'user',
        existing_comment='Calculates y-intercept of the least-squares-fit linear equation determined by the (X, Y) pairs.',
        schema=None
    )

    with op.batch_alter_table('user_exercise', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text('unique_rowid()'))
        batch_op.alter_column('user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('exercise_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_user_exercise_user_id'), ['user_id'], unique=False)
        batch_op.drop_table_comment(
        'user_exercise',
        existing_comment='Calculates y-intercept of the least-squares-fit linear equation determined by the (X, Y) pairs.',
        schema=None
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_exercise', schema=None) as batch_op:
        batch_op.create_table_comment(
        'user_exercise',
        'Calculates y-intercept of the least-squares-fit linear equation determined by the (X, Y) pairs.',
        existing_comment=None,
        schema=None
    )
        batch_op.drop_index(batch_op.f('ix_user_exercise_user_id'))
        batch_op.alter_column('exercise_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text('unique_rowid()'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_table_comment(
        'user',
        'Calculates y-intercept of the least-squares-fit linear equation determined by the (X, Y) pairs.',
        existing_comment=None,
        schema=None
    )
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text('unique_rowid()'))

    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.create_table_comment(
        'exercise',
        'Calculates y-intercept of the least-squares-fit linear equation determined by the (X, Y) pairs.',
        existing_comment=None,
        schema=None
    )
        batch_op.drop_index(batch_op.f('ix_exercise_category'))
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text('unique_rowid()'))

    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    comment="Shows all defined Spatial Reference Identifiers (SRIDs). Matches PostGIS' spatial_ref_sys table."
    )
    op.create_table('geography_columns',
    sa.Column('f_table_catalog', sa.String(), autoincrement=False, nullable=True),
    sa.Column('f_table_schema', sa.String(), autoincrement=False, nullable=True),
    sa.Column('f_table_name', sa.String(), autoincrement=False, nullable=True),
    sa.Column('f_geography_column', sa.String(), autoincrement=False, nullable=True),
    sa.Column('coord_dimension', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('srid', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    comment="Shows all defined geography columns. Matches PostGIS' geography_columns functionality."
    )
    op.create_table('geometry_columns',
    sa.Column('f_table_catalog', sa.String(), autoincrement=False, nullable=True),
    sa.Column('f_table_schema', sa.String(), autoincrement=False, nullable=True),
    sa.Column('f_table_name', sa.String(), autoincrement=False, nullable=True),
    sa.Column('f_geometry_column', sa.String(), autoincrement=False, nullable=True),
    sa.Column('coord_dimension', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('srid', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    comment="Shows all defined geometry columns. Matches PostGIS' geometry_columns functionality."
    )
    # ### end Alembic commands ###
