from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73c9dbc8e848'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('g_auth_verify', sa.Boolean(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('token'),
    sa.UniqueConstraint('username')
    )
    op.create_table('wine',
    sa.Column('wine_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('region', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('wine_id')
    )
    op.create_table('wine_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wine_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['wine_id'], ['wine.wine_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'wine_id')
    )
    # REMOVE THESE LINES - Cannot modify system tables
    # op.drop_table('geography_columns')
    # op.drop_table('geometry_columns')
    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # REMOVE THESE LINES - Cannot create system tables
    # op.create_table('geography_columns',
    # sa.Column('f_table_catalog', sa.String(), autoincrement=False, nullable=True),
    # sa.Column('f_table_schema', sa.String(), autoincrement=False, nullable=True),
    # sa.Column('f_table_name', sa.String(), autoincrement=False, nullable=True),
    # sa.Column('f_geography_column', sa.String(), autoincrement=False, nullable=True),
    # sa.Column('coord_dimension', sa.BIGINT(), autoincrement=False, nullable=True),
    # sa.Column('srid', sa.BIGINT(), autoincrement=False, nullable=True),
    # sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    # comment="Shows all defined geography columns. Matches PostGIS' geography_columns functionality."
    # )
    # op.create_table('geometry_columns',
    # sa.Column('f_table_catalog', sa.String(), autoincrement=False, nullable=True),
    # sa.Column('f_table_schema', sa.String(), autoincrement=False, nullable=True),
    # sa.Column('f_table_name', sa.String(), autoincrement=False, nullable=True),
    # sa.Column('f_geometry_column', sa.String(), autoincrement=False, nullable=True),
    # sa.Column('coord_dimension', sa.BIGINT(), autoincrement=False, nullable=True),
    # sa.Column('srid', sa.BIGINT(), autoincrement=False, nullable=True),
    # sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    # comment="Shows all defined geometry columns. Matches PostGIS' geometry_columns functionality."
    # )
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.BIGINT(), autoincrement=False, nullable=True),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.BIGINT(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # comment="Shows all defined Spatial Reference Identifiers (SRIDs). Matches PostGIS' spatial_ref_sys table."
    # )
    op.drop_table('wine_users')
    op.drop_table('wine')
    op.drop_table('user')
    # ### end Alembic commands ###