"""empty message

Revision ID: d02a6c7d8da1
Revises: acedb7f015d7
Create Date: 2025-04-16 14:08:02.269338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd02a6c7d8da1'
down_revision = 'acedb7f015d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spatial_ref_sys')
    op.drop_table('geography_columns')
    op.drop_table('geometry_columns')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text('unique_rowid()'))
        batch_op.drop_table_comment(
        'user',
        existing_comment='Calculates y-intercept of the least-squares-fit linear equation determined by the (X, Y) pairs.',
        schema=None
    )

    with op.batch_alter_table('wine', schema=None) as batch_op:
        batch_op.alter_column('wine_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text('unique_rowid()'))
        batch_op.drop_table_comment(
        'wine',
        existing_comment='Calculates y-intercept of the least-squares-fit linear equation determined by the (X, Y) pairs.',
        schema=None
    )

    with op.batch_alter_table('wine_users', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('wine_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_table_comment(
        'wine_users',
        existing_comment='Calculates y-intercept of the least-squares-fit linear equation determined by the (X, Y) pairs.',
        schema=None
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wine_users', schema=None) as batch_op:
        batch_op.create_table_comment(
        'wine_users',
        'Calculates y-intercept of the least-squares-fit linear equation determined by the (X, Y) pairs.',
        existing_comment=None,
        schema=None
    )
        batch_op.alter_column('wine_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)

    with op.batch_alter_table('wine', schema=None) as batch_op:
        batch_op.create_table_comment(
        'wine',
        'Calculates y-intercept of the least-squares-fit linear equation determined by the (X, Y) pairs.',
        existing_comment=None,
        schema=None
    )
        batch_op.alter_column('wine_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text('unique_rowid()'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_table_comment(
        'user',
        'Calculates y-intercept of the least-squares-fit linear equation determined by the (X, Y) pairs.',
        existing_comment=None,
        schema=None
    )
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text('unique_rowid()'))

    op.create_table('geometry_columns',
    sa.Column('f_table_catalog', sa.String(), autoincrement=False, nullable=True),
    sa.Column('f_table_schema', sa.String(), autoincrement=False, nullable=True),
    sa.Column('f_table_name', sa.String(), autoincrement=False, nullable=True),
    sa.Column('f_geometry_column', sa.String(), autoincrement=False, nullable=True),
    sa.Column('coord_dimension', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('srid', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    comment="Shows all defined geometry columns. Matches PostGIS' geometry_columns functionality."
    )
    op.create_table('geography_columns',
    sa.Column('f_table_catalog', sa.String(), autoincrement=False, nullable=True),
    sa.Column('f_table_schema', sa.String(), autoincrement=False, nullable=True),
    sa.Column('f_table_name', sa.String(), autoincrement=False, nullable=True),
    sa.Column('f_geography_column', sa.String(), autoincrement=False, nullable=True),
    sa.Column('coord_dimension', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('srid', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    comment="Shows all defined geography columns. Matches PostGIS' geography_columns functionality."
    )
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    comment="Shows all defined Spatial Reference Identifiers (SRIDs). Matches PostGIS' spatial_ref_sys table."
    )
    # ### end Alembic commands ###
